# Site settings
title: Bujia Project Music
email: bujiaprojectmusic@gmail.com
description: > Â¡Hola a todos los amantes de las seis y cuatro cuerdas! ğŸ¸âœ¨ Estamos emocionados de darles la bienvenida a nuestro proyecto, donde la pasiÃ³n por la mÃºsica y la magia de las guitarras y bajos se unen. ğŸ’«ğŸ¶ Si tu instrumento necesita un poco de cariÃ±o, estamos aquÃ­ para hacerlo sonar como nunca antes. ğŸ› ï¸ğŸµ Ãšnete a nosotros en este viaje musical y juntos haremos que la mÃºsica suene mejor que nunca. ğŸ¤˜ğŸ˜„
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
